/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corediagnosticsystem;

import classes.CommonMethod;
import classes.DBQueries;
import classes.GlobalVariables;
import classes.SwingUtils;
import classes.ImageFileView;
import classes.ImageFilter;
import classes.ImagePreview;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author ACC
 */
public class dlgEmployeesAdd extends javax.swing.JDialog {
    private frmMain main;
    private boolean INSERT=false;
     private JFileChooser fc;
    private File file;
    private boolean UPLOADED = false, HASIMAGE = false;
    private FileInputStream fin;
    /**
     * Creates new form dlgEmployeesAdd
     */
    public dlgEmployeesAdd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.main = (frmMain) parent;
        CommonMethod.setDialogScreenLocation(main, this);
        txtCellphoneNo.setDocument(new JTextFieldLimit(11));
        CommonMethod.getAutoEmployeeID(lblEmployeeID);
        CommonMethod.getPositionList(cmbPosition);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txtLastname = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        txtMiddlename = new javax.swing.JTextField();
        txtExtension = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCellphoneNo = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cmbGender = new javax.swing.JComboBox<>();
        dcBirthDate = new com.toedter.calendar.JDateChooser();
        ckbShowPassword = new javax.swing.JCheckBox();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        cmbPosition = new javax.swing.JComboBox<>();
        txtLicenseNo = new javax.swing.JTextField();
        cmbEmploymentStatus = new javax.swing.JComboBox<>();
        ckbShowPassword1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();

        jFileChooser1.setDialogTitle("Select Image");
        jFileChooser1.setFileView(new ImageFileView());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CORE Diagnostic and Urgent Care Center, Inc.");
        setPreferredSize(new java.awt.Dimension(660, 660));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel12.setLayout(new java.awt.GridLayout(4, 0, 0, 1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Lastname");
        jPanel12.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Firstname:");
        jPanel12.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Middlename:");
        jPanel12.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Extension:");
        jPanel12.add(jLabel14);

        jPanel13.setLayout(new java.awt.GridLayout(4, 0, 0, 3));

        txtLastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLastname.setToolTipText("Input Lastname!");
        txtLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastnameKeyTyped(evt);
            }
        });
        jPanel13.add(txtLastname);

        txtFirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstname.setToolTipText("Input Firstname!");
        txtFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstnameKeyTyped(evt);
            }
        });
        jPanel13.add(txtFirstname);

        txtMiddlename.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMiddlename.setToolTipText("Input Middlename!");
        txtMiddlename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMiddlenameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMiddlenameKeyTyped(evt);
            }
        });
        jPanel13.add(txtMiddlename);

        txtExtension.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtExtension.setToolTipText("Input Extensionname!");
        txtExtension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExtensionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExtensionKeyTyped(evt);
            }
        });
        jPanel13.add(txtExtension);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 185));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contacts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Address:");

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddress.setToolTipText("Input Address!");
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Cellphone No.");

        txtCellphoneNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCellphoneNo.setToolTipText("Input Cellphone No. here!");
        txtCellphoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCellphoneNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCellphoneNoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCellphoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtCellphoneNo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender/B-day/Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 0, 1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Gender:");
        jPanel3.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Date of Birth:");
        jPanel3.add(jLabel1);

        jPanel4.setLayout(new java.awt.GridLayout(3, 0, 0, 3));

        cmbGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", "MALE", "FEMALE" }));
        cmbGender.setToolTipText("Select Gender!");
        jPanel4.add(cmbGender);

        dcBirthDate.setToolTipText("Enter Birthday here! ex. April 7, 1990");
        dcBirthDate.setDateFormatString("MMMM d, yyyy");
        dcBirthDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(dcBirthDate);

        ckbShowPassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbShowPasswordItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(ckbShowPassword))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setLayout(new java.awt.BorderLayout());

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/noimage.png"))); // NOI18N
        lblImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(lblImage, java.awt.BorderLayout.CENTER);

        btnUpload.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpload.setText("UPLOAD PHOTO....");
        btnUpload.setPreferredSize(new java.awt.Dimension(73, 35));
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel18.add(btnUpload, java.awt.BorderLayout.PAGE_END);

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 16, 170, 162));

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imployment Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel20.setLayout(new java.awt.GridLayout(3, 0, 0, 1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Position:");
        jPanel20.add(jLabel18);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("License No.");
        jPanel20.add(jLabel19);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Emp. Status:");
        jPanel20.add(jLabel22);

        jPanel21.setLayout(new java.awt.GridLayout(3, 0, 0, 3));

        cmbPosition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", "MALE", "FEMALE" }));
        cmbPosition.setToolTipText("Select Position!");
        jPanel21.add(cmbPosition);

        txtLicenseNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLicenseNo.setToolTipText("Enter License No.!");
        txtLicenseNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLicenseNoKeyTyped(evt);
            }
        });
        jPanel21.add(txtLicenseNo);

        cmbEmploymentStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbEmploymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", "EMPLOYED", "UNEMPLOYED" }));
        cmbEmploymentStatus.setSelectedIndex(1);
        cmbEmploymentStatus.setToolTipText("Select Employment Status!");
        cmbEmploymentStatus.setEnabled(false);
        jPanel21.add(cmbEmploymentStatus);

        ckbShowPassword1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbShowPassword1ItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_icon.png"))); // NOI18N
        jLabel7.setToolTipText("Click to add new position!");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(ckbShowPassword1))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ckbShowPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addGap(38, 38, 38)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(jSeparator2, java.awt.BorderLayout.PAGE_START);

        jPanel9.setPreferredSize(new java.awt.Dimension(588, 80));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear_icon.png"))); // NOI18N
        jButton1.setMnemonic('C');
        jButton1.setText("CLEAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_icon.png"))); // NOI18N
        jButton2.setMnemonic('S');
        jButton2.setText("SAVE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel6.setPreferredSize(new java.awt.Dimension(588, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel10.setText("   ADDING NEW EMPLOYEE");
        jPanel6.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel16.setPreferredSize(new java.awt.Dimension(255, 48));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("EMPLOYEE ID:");
        jPanel16.add(jLabel8, java.awt.BorderLayout.WEST);

        lblEmployeeID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmployeeID.setForeground(new java.awt.Color(255, 51, 0));
        lblEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployeeID.setText("CD-2017-001");
        lblEmployeeID.setToolTipText("Patiend ID");
        lblEmployeeID.setPreferredSize(new java.awt.Dimension(250, 22));
        jPanel16.add(lblEmployeeID, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel16, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastnameKeyReleased
        txtLastname.setText(txtLastname.getText().toUpperCase());
    }//GEN-LAST:event_txtLastnameKeyReleased

    private void txtLastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastnameKeyTyped

    }//GEN-LAST:event_txtLastnameKeyTyped

    private void txtFirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstnameKeyReleased
        txtFirstname.setText(txtFirstname.getText().toUpperCase());
    }//GEN-LAST:event_txtFirstnameKeyReleased

    private void txtFirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstnameKeyTyped

    }//GEN-LAST:event_txtFirstnameKeyTyped

    private void txtMiddlenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMiddlenameKeyReleased
        txtMiddlename.setText(txtMiddlename.getText().toUpperCase());
    }//GEN-LAST:event_txtMiddlenameKeyReleased

    private void txtMiddlenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMiddlenameKeyTyped

    }//GEN-LAST:event_txtMiddlenameKeyTyped

    private void txtExtensionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExtensionKeyReleased
        txtExtension.setText(txtExtension.getText().toUpperCase());
    }//GEN-LAST:event_txtExtensionKeyReleased

    private void txtExtensionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExtensionKeyTyped

    }//GEN-LAST:event_txtExtensionKeyTyped

    private void txtLicenseNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicenseNoKeyTyped
        CommonMethod.setOnlyNumbersAccepted(evt);
    }//GEN-LAST:event_txtLicenseNoKeyTyped
private void ClearFields() {
        txtLastname.setText("");
        txtFirstname.setText("");
        txtMiddlename.setText("");
        txtExtension.setText("");
        cmbGender.setSelectedIndex(0);
        txtAddress.setText("");
        txtLicenseNo.setText("");
        txtLastname.requestFocus();
        dcBirthDate.setDate(null);
        cmbPosition.setSelectedIndex(0);
        txtCellphoneNo.setText("");
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/noimage.png"))); // NOI18N
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Do you want to clear all the fields?", "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            ClearFields();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String lname = txtLastname.getText().trim();
        String fname = txtFirstname.getText().trim();
        String mname = txtMiddlename.getText().trim();
        String ext = txtExtension.getText().trim();
        String gender = cmbGender.getSelectedItem().toString();
        Date bdate = dcBirthDate.getDate();
        
        String position = cmbPosition.getSelectedItem().toString();
        String licenseno = txtLicenseNo.getText().trim();
        String status = cmbEmploymentStatus.getSelectedItem().toString();
        String address = txtAddress.getText().trim();
        String contact = txtCellphoneNo.getText().trim();
        String employeeID = lblEmployeeID.getText().trim();
        
        if (employeeID.equals("####-######")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No employee ID generated. Please contact the System Administrator for help!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLastname.requestFocus();
            return;
        }
        if (lname.equals("")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No lastname found. Please enter employee lastname!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLastname.requestFocus();
            return;
        }
        if (fname.equals("")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No firstname found. Please enter employee firstname!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtFirstname.requestFocus();
            return;
        }
        if (gender.equals("-SELECT-")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No gender selected. Please select employee gender!", "ERROR", JOptionPane.ERROR_MESSAGE);
            cmbGender.requestFocus();
            return;
        }
        if (bdate == null) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No birth date found. \nPlease enter employee birth date! or enter a valid birthdate! ex. April 7, 1990", "ERROR", JOptionPane.ERROR_MESSAGE);
            dcBirthDate.requestFocus();
            return;
        }
        if (bdate.after(new java.util.Date())) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Invalid birth date found. Please enter employee valid birthdate ex. April 7, 1990!", "ERROR", JOptionPane.ERROR_MESSAGE);
            dcBirthDate.requestFocus();
            return;
        }
        
         if (position.equals("-SELECT-")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No position selected. Please select employee position!", "ERROR", JOptionPane.ERROR_MESSAGE);
            cmbPosition.requestFocus();
            return;
        }
         if (status.equals("-SELECT-")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No employment status selected. Please select employee status!", "ERROR", JOptionPane.ERROR_MESSAGE);
            cmbEmploymentStatus.requestFocus();
            return;
        }
        if (address.equals("")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No address found. Please enter employee address!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtAddress.requestFocus();
            return;
        }
        if (!contact.equals("")) {
            System.out.println(contact.length());
            if (contact.length() != 11) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Invalid cellphone no. found. Please enter 11-digits cellphone no.!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtLicenseNo.requestFocus();
                return;
            }
        }
        if(UPLOADED==false){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No image uploaded found. Please upload employee picture!", "ERROR", JOptionPane.ERROR_MESSAGE);
            btnUpload.requestFocus();
            return;
        }
        PreparedStatement ps = null;
        DBQueries db = new DBQueries();
        try {
            int CONFIRM = JOptionPane.showConfirmDialog(this, "Are all information correct?", "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (CONFIRM == JOptionPane.YES_OPTION) {
                db.ConnectToDatabase();
                boolean exist = db.checkExistingEmployeeInfo(lname, fname, mname);
                if (exist) {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, lname + ", " + fname + " " + mname + " already exist in the database record!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txtLastname.requestFocus();
                    return;
                }
                ps = db.con.prepareStatement("INSERT INTO employee_tb(employee_id,emp_lastname,emp_firstname,emp_middlename,emp_extension,emp_birthdate,"
                        + "emp_gender,position_id,license_no,emp_address,emp_cellphoneno,emp_status,date_registered,image) "
                        + "VALUES(?,?,?,?,?,'"+bdate+"',?,"
                        + "(SELECT position_id from position_tb WHERE position_name=?),?,?,?,?,now(),?)");
                //ps = db.con.prepareStatement("INSERT INTO employee_tb VALUES('" + employeeID + "','" + lnamse + "','" + fname + "','" + mname + "','" + ext + "','" + bdate + "','" + gender + "',(SELECT position_id from position_tb WHERE position_name='" + position + "'),'" + licenseno + "','" + address + "','" + contact + "','" + status+ "','" + username + "',md5('" + password + "'),now())");
                ps.setString(1, employeeID);
                ps.setString(2, lname);
                ps.setString(3, fname);
                ps.setString(4, mname);
                ps.setString(5, ext);
                ps.setString(6, gender);
                ps.setString(7, position);
                ps.setString(8, licenseno);
                ps.setString(9, address);
                ps.setString(10, contact);
                ps.setString(11, status);
                ps.setBinaryStream(12, fin, (int) file.length());
                int i=ps.executeUpdate();
                
                 //= db.insertEmployeeInformation(employeeID, lname, fname, mname, ext, gender, bdate,username,password,position,licenseno,status, address, contact);
                if (i > 0) {
                    INSERT = true;
                    UPLOADED = false;
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Inserted Successfully!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    int CONFIRM2 = JOptionPane.showConfirmDialog(this, "Do you want to add more employee info?", "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (CONFIRM2 == JOptionPane.YES_OPTION) {
                        CommonMethod.getAutoEmployeeID(lblEmployeeID);
                        ClearFields();
                    } else {
                        this.dispose();
                        main.showLoading(GlobalVariables.FORM_EMPLOYEES, "Refreshing Employee Records....");
                    }

                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Insert Failed! Please contact the System Administrator for asssisstance and help.", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (HeadlessException | SQLException e) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (db.con != null) {
                db.closeConnection();
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        txtAddress.setText(txtAddress.getText().toUpperCase());
    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressKeyTyped

    private void txtCellphoneNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCellphoneNoKeyTyped
         CommonMethod.setOnlyNumbersAccepted(evt);
    }//GEN-LAST:event_txtCellphoneNoKeyTyped

    private void ckbShowPasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbShowPasswordItemStateChanged
     
    }//GEN-LAST:event_ckbShowPasswordItemStateChanged

    private void txtCellphoneNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCellphoneNoKeyReleased
      
    }//GEN-LAST:event_txtCellphoneNoKeyReleased

    private void ckbShowPassword1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbShowPassword1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbShowPassword1ItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        SwingUtils.fadeOut(this);
    }//GEN-LAST:event_formWindowClosing

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
       int height = lblImage.getHeight() - 2;
        int width = lblImage.getWidth();
        
        if (fc == null) {
            fc = new JFileChooser();
            fc.setCurrentDirectory(new java.io.File("../.././Picture"));
            //Add a custom file filter and disable the default
            //(Accept All) file filter.
            fc.addChoosableFileFilter(new ImageFilter());
            fc.setAcceptAllFileFilterUsed(false);
            //Add custom icons for file types.
            fc.setFileView(new ImageFileView());
            //Add the preview pane.
            fc.setAccessory(new ImagePreview(fc));
        }
        //Show it.
        int returnVal = fc.showDialog(this, "Select Image");
        //Process the results.
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            if (file.isFile()) {
                try {
                    fin = new FileInputStream(file);
                    ImageIcon image = new ImageIcon(file.getAbsolutePath());
                    Image img = image.getImage();
                    Image newimg = img.getScaledInstance(width, height, java.awt.Image.SCALE_DEFAULT);
                    lblImage.setText("");
                    lblImage.setIcon(new ImageIcon(newimg));
                    String tooltip = "<html>" + "<center>" + "" + "<img height=\"500\" width=\"500\" src=\"file:" + file + "\">" + "</center></html>";
                    lblImage.setToolTipText(tooltip);
                    btnUpload.setText("CHANGE IMAGE");
                    UPLOADED = true;
                } catch (Exception e) {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                //studnumber.setText(file.getName().substring(0,file.getName().length()-4));
            }

        }
        //Reset the file chooser for the next time it's shown.
        fc.setSelectedFile(null);
    }//GEN-LAST:event_btnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgEmployeesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgEmployeesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgEmployeesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgEmployeesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgEmployeesAdd dialog = new dlgEmployeesAdd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpload;
    private javax.swing.JCheckBox ckbShowPassword;
    private javax.swing.JCheckBox ckbShowPassword1;
    private javax.swing.JComboBox<String> cmbEmploymentStatus;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbPosition;
    private com.toedter.calendar.JDateChooser dcBirthDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCellphoneNo;
    private javax.swing.JTextField txtExtension;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtMiddlename;
    // End of variables declaration//GEN-END:variables
}
