 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corediagnosticsystem;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author GgClaud
 */
public class dlgLoading extends javax.swing.JDialog {

    private frmMain main;
    private Point p;

    /**
     * Creates new form dlgLoading
     */
    public dlgLoading(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        //Dimension main = parent.
        int kiri = (layar.width - this.getSize().width) / 2;
        int atas = (layar.height - this.getSize().height) / 2;
        setLocation(kiri, atas);
        //setLookAndFeel();
    }

    public dlgLoading(frmMain parent, boolean modal, String comment) {
       super(parent, modal);
        initComponents();
        //Dimension main = parent.getPreferredSize();
        //int width = main.width/2;
        //int height = main.height/2;
        //parent.getlo
        lblOutput.setText(comment);
        Point dime = parent.getLocationOnScreen();
        Dimension di = parent.getSize();
        int parentWidth = di.width / 2;
        int parentHeight = di.height / 2;
        int thisWindowWidth = this.getWidth() / 2;
        int thisWindowHeight = this.getHeight() / 2;
        int x = (int) dime.getX() + (parentWidth - thisWindowWidth);
        int y = (int) dime.getY() + (parentHeight - thisWindowHeight);
        setLocation(x, y);
    }

     public dlgLoading(JDialog parent, boolean modal, String comment) {
       super(parent, modal);
        initComponents();
        //Dimension main = parent.getPreferredSize();
        //int width = main.width/2;
        //int height = main.height/2;
        //parent.getlo
        lblOutput.setText(comment);
        Point dime = parent.getLocationOnScreen();
        Dimension di = parent.getSize();
        int parentWidth = di.width / 2;
        int parentHeight = di.height / 2;
        int thisWindowWidth = this.getWidth() / 2;
        int thisWindowHeight = this.getHeight() / 2;
        int x = (int) dime.getX() + (parentWidth - thisWindowWidth);
        int y = (int) dime.getY() + (parentHeight - thisWindowHeight);
        setLocation(x, y);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLoading = new javax.swing.JPanel();
        lblOutput = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Loading....");
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setUndecorated(true);
        setOpacity(0.9F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlLoading.setLayout(new java.awt.GridLayout(3, 0));

        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutput.setText("output");
        pnlLoading.add(lblOutput);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ajax-loader3.gif"))); // NOI18N
        pnlLoading.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please wait....");
        pnlLoading.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 27, 11, 27);
        getContentPane().add(pnlLoading, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // setLookAndFeel();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgLoading dialog = new dlgLoading(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel lblOutput;
    protected javax.swing.JPanel pnlLoading;
    // End of variables declaration//GEN-END:variables
}
