/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corediagnosticsystem;

import classes.AutoCompleteDBLink;
import classes.AutoTextComplete;
import classes.CommonMethod;
import classes.DBQueries;
import classes.GlobalVariables;
import classes.SwingUtils;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ACC
 */
public class dlgPatientNew extends javax.swing.JDialog {

    public static boolean INSERT = false;
    private frmMain main;

    /**
     * Creates new form dlgNewPatient
     */
    public dlgPatientNew(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          //initialize autocomplete
        AutoComplete();
        this.main = (frmMain) parent;
        //  Dimension dime = Toolkit.getDefaultToolkit().getScreenSize();
        //int width = (dime.width - this.getSize().width)/2;
        // int height = (dime.height - this.getSize().height)/2;
        //setLocation(width,height);
        //set screen location at the center
        Point dime = parent.getLocationOnScreen();
        Dimension di = parent.getSize();
        int parentWidth = di.width / 2;
        int parentHeight = di.height / 2;
        int thisWindowWidth = this.getWidth() / 2;
        int thisWindowHeight = this.getHeight() / 2;
        int x = (int) dime.getX() + (parentWidth - thisWindowWidth);
        int y = (int) dime.getY() + (parentHeight - thisWindowHeight);
        setLocation(x, y);
        //autogenerate patient id upon window is open
        CommonMethod.getAutoPatientID(lblPatientID);
        //set character limit
        txtContactNo.setDocument(new JTextFieldLimit(12));
      

    }

    private void AutoComplete() {

        DBQueries db = new DBQueries();
        try {
            db.ConnectToDatabase();
            JTextField lname = txtLastname;
            //call autocomplete method
            AutoTextComplete autolname = new AutoTextComplete(lname);
            AutoTextComplete autofname = new AutoTextComplete(txtFirstname);
            AutoTextComplete automname = new AutoTextComplete(txtMiddlename);
            AutoTextComplete autoename = new AutoTextComplete(txtExtension);
            AutoTextComplete autoaddress = new AutoTextComplete(txtAddress);
            new AutoCompleteDBLink(autolname, "select distinct lastname from patient_tb order by lastname;", db.con);
            new AutoCompleteDBLink(autofname, "select distinct firstname from patient_tb order by firstname;", db.con);
            new AutoCompleteDBLink(automname, "select distinct middlename from patient_tb order by middlename;", db.con);
            new AutoCompleteDBLink(autoename, "select distinct extension from patient_tb order by extension;", db.con);
            new AutoCompleteDBLink(autoaddress, "select distinct address from patient_tb order by address;", db.con);

        } catch (Exception e) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (db.con != null) {
                db.closeConnection();
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cmbGender = new javax.swing.JComboBox<>();
        dcBirthDate = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txtLastname = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        txtMiddlename = new javax.swing.JTextField();
        txtExtension = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JFormattedTextField();
        lblChangeAuto = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CORE Diagnostic and Urgent Care Center, Inc.");
        setPreferredSize(new java.awt.Dimension(690, 460));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setPreferredSize(new java.awt.Dimension(588, 250));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender/B-day", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(4, 0, 0, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Gender:");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Date of Birth:");
        jPanel1.add(jLabel2);

        jPanel4.setLayout(new java.awt.GridLayout(4, 0, 0, 3));

        cmbGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", "MALE", "FEMALE" }));
        cmbGender.setToolTipText("Select Gender!");
        jPanel4.add(cmbGender);

        dcBirthDate.setToolTipText("Enter Birthday here! ex. April 7, 1990");
        dcBirthDate.setDateFormatString("MMMM d, yyyy");
        dcBirthDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(dcBirthDate);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel12.setLayout(new java.awt.GridLayout(4, 0, 0, 1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Lastname");
        jPanel12.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Firstname:");
        jPanel12.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Middlename:");
        jPanel12.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Extension:");
        jPanel12.add(jLabel14);

        jPanel13.setLayout(new java.awt.GridLayout(4, 0, 0, 3));

        txtLastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLastname.setToolTipText("Input Lastname!");
        txtLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastnameKeyTyped(evt);
            }
        });
        jPanel13.add(txtLastname);

        txtFirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstname.setToolTipText("Input Firstname!");
        txtFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstnameKeyTyped(evt);
            }
        });
        jPanel13.add(txtFirstname);

        txtMiddlename.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMiddlename.setToolTipText("Input Middlename!");
        txtMiddlename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMiddlenameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMiddlenameKeyTyped(evt);
            }
        });
        jPanel13.add(txtMiddlename);

        txtExtension.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtExtension.setToolTipText("Input Extensionname!");
        txtExtension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExtensionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExtensionKeyTyped(evt);
            }
        });
        jPanel13.add(txtExtension);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contacts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Address:");

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddress.setToolTipText("Input Address!");
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Cellphone No.");

        txtContactNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContactNo)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtContactNo))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(588, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel10.setText("   ADDING NEW PATIENT INFO.");
        jLabel10.setPreferredSize(new java.awt.Dimension(300, 21));
        jPanel6.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 48));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("PATIENT ID:");
        jPanel2.add(jLabel5, java.awt.BorderLayout.WEST);

        try {
            lblPatientID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        lblPatientID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblPatientID.setToolTipText("Patient No.");
        lblPatientID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lblPatientID.setEnabled(false);
        lblPatientID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(lblPatientID, java.awt.BorderLayout.CENTER);

        lblChangeAuto.setForeground(new java.awt.Color(255, 51, 0));
        lblChangeAuto.setText("<html><b><u>Change..</u></b></html>");
        lblChangeAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblChangeAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblChangeAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeAutoMouseClicked(evt);
            }
        });
        jPanel2.add(lblChangeAuto, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel2, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(jSeparator2, java.awt.BorderLayout.PAGE_START);

        jPanel9.setPreferredSize(new java.awt.Dimension(588, 80));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear_icon.png"))); // NOI18N
        jButton1.setMnemonic('C');
        jButton1.setText("CLEAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_icon.png"))); // NOI18N
        jButton2.setMnemonic('S');
        jButton2.setText("SAVE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastnameKeyTyped

    }//GEN-LAST:event_txtLastnameKeyTyped

    private void txtFirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstnameKeyTyped

    }//GEN-LAST:event_txtFirstnameKeyTyped

    private void txtMiddlenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMiddlenameKeyTyped

    }//GEN-LAST:event_txtMiddlenameKeyTyped

    private void txtExtensionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExtensionKeyTyped

    }//GEN-LAST:event_txtExtensionKeyTyped

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped

    }//GEN-LAST:event_txtAddressKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String lname = txtLastname.getText().trim();
        String fname = txtFirstname.getText().trim();
        String mname = txtMiddlename.getText().trim();
        String ext = txtExtension.getText().trim();
        String gender = cmbGender.getSelectedItem().toString();
        Date bdate = dcBirthDate.getDate();
        String address = txtAddress.getText().trim();
        String contact = txtContactNo.getText().trim();
        String patientID = lblPatientID.getText().trim();
        if (patientID.equals("###-###-####")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No Patiend ID generated. Please contact the System Administrator for help!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLastname.requestFocus();
            return;
        }
        if (lname.equals("")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No lastname found. Please enter patient lastname!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLastname.requestFocus();
            return;
        }
        if (fname.equals("")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No firstname found. Please enter patient firstname!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtFirstname.requestFocus();
            return;
        }
        if (gender.equals("-SELECT-")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No gender selected. Please select patient gender!", "ERROR", JOptionPane.ERROR_MESSAGE);
            cmbGender.requestFocus();
            return;
        }
        if (bdate == null) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No birth date found.\n Please enter patient birth date! or enter a valid birthdate! ex. April 7, 1990", "ERROR", JOptionPane.ERROR_MESSAGE);
            dcBirthDate.requestFocus();
            return;
        }
        if (bdate.after(new java.util.Date())) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Invalid birth date found. Please enter patient valid birthdate! ex. April 7, 1990", "ERROR", JOptionPane.ERROR_MESSAGE);
            dcBirthDate.requestFocus();
            return;
        }
        if (address.equals("")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No address found. Please enter patient address!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtAddress.requestFocus();
            return;
        }
        if (!contact.equals("")) {

            if (contact.length() != 11) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Invalid cellphone no. found. Please enter 11-digits cellphone no.!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtContactNo.requestFocus();
                return;
            }

        }
        DBQueries db = new DBQueries();
        try {
            int CONFIRM = JOptionPane.showConfirmDialog(this, "Are all information correct?", "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (CONFIRM == JOptionPane.YES_OPTION) {
                db.ConnectToDatabase();
                boolean exist = db.checkExistingPatienInfo(lname, fname, mname);
                if (exist) {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, lname + ", " + fname + " " + mname + " already exist in the database record!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txtLastname.requestFocus();
                    return;
                }
                int i = db.insertPatientInformation(CommonMethod.TrimPatientID(patientID), lname, fname, mname, ext, gender, bdate, address, contact);
                if (i > 0) {
                    INSERT = true;
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Inserted Successfully!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    int CONFIRM2 = JOptionPane.showConfirmDialog(this, "Do you want to add more patient info?", "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (CONFIRM2 == JOptionPane.YES_OPTION) {
                        CommonMethod.getAutoPatientID(lblPatientID);
                        ClearFields();
                    } else {
                        this.dispose();
                        main.showLoading(GlobalVariables.FORM_PATIENT, "Refreshing Patient Records....");
                    }

                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Insert Failed!", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (HeadlessException e) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (db.con != null) {
                db.closeConnection();
            }

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtLastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastnameKeyReleased
        txtLastname.setText(txtLastname.getText().toUpperCase());
    }//GEN-LAST:event_txtLastnameKeyReleased

    private void txtFirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstnameKeyReleased
        txtFirstname.setText(txtFirstname.getText().toUpperCase());
    }//GEN-LAST:event_txtFirstnameKeyReleased

    private void txtMiddlenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMiddlenameKeyReleased
        txtMiddlename.setText(txtMiddlename.getText().toUpperCase());
    }//GEN-LAST:event_txtMiddlenameKeyReleased

    private void txtExtensionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExtensionKeyReleased
        txtExtension.setText(txtExtension.getText().toUpperCase());
    }//GEN-LAST:event_txtExtensionKeyReleased

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        txtAddress.setText(txtAddress.getText().toUpperCase());
    }//GEN-LAST:event_txtAddressKeyReleased
    private void ClearFields() {
        txtLastname.setText("");
        txtFirstname.setText("");
        txtMiddlename.setText("");
        txtExtension.setText("");
        cmbGender.setSelectedIndex(0);
        dcBirthDate.setDate(null);
        txtAddress.setText("");
        txtContactNo.setText("");
        txtLastname.requestFocus();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Do you want to clear all the fields?", "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            ClearFields();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        SwingUtils.fadeOut(this);
        if (INSERT == true) {
            main.showLoading(GlobalVariables.FORM_PATIENT, "Refreshing Patient Records....");
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyTyped
        CommonMethod.setOnlyNumbersAccepted(evt);
    }//GEN-LAST:event_txtContactNoKeyTyped

    private void lblChangeAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeAutoMouseClicked
        if (!lblPatientID.isEnabled() && lblChangeAuto.getText().equals("<html><b><u>Change..</u></b></html>")) {
            lblPatientID.setEnabled(true);
            lblPatientID.requestFocusInWindow();
            lblChangeAuto.setText("<html><b><u>Auto..</u></b></html>");
        } else {
            CommonMethod.getAutoPatientID(lblPatientID);
            lblChangeAuto.setText("<html><b><u>Change..</u></b></html>");
            lblPatientID.setEnabled(false);
        }
    }//GEN-LAST:event_lblChangeAutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgPatientNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgPatientNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgPatientNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgPatientNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgPatientNew dialog = new dlgPatientNew(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGender;
    private com.toedter.calendar.JDateChooser dcBirthDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblChangeAuto;
    private javax.swing.JFormattedTextField lblPatientID;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtExtension;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtMiddlename;
    // End of variables declaration//GEN-END:variables
}
