/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corediagnosticsystem;

import classes.CommonMethod;
import classes.DBQueries;
import classes.GlobalVariables;
import classes.JComboBoxSetter;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ACC
 */
public class dlgSystemInformation extends javax.swing.JDialog {

    private frmMain main;

    /**
     * Creates new form dlgSystemInformation
     */
    public dlgSystemInformation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.main = (frmMain) parent;
        CommonMethod.setDialogScreenLocation(main, this);
        checkSystemInfo();
        checkRole();
    }
    private void checkRole(){
        if(!frmMain.SYSTEMROLE.equals(GlobalVariables.ROLE_ADMINISTRATOR)){
            btnSave.setVisible(false);
        }
    }
    private void checkSystemInfo() {

        DBQueries db = new DBQueries();
        try {
            db.ConnectToDatabase();
            db.querySystemInfo();
            while (db.rs.next()) {
                if (db.rs.getString("attributes").equals(GlobalVariables.COMPANY_NAME)) {
                    txtCompanyName.setText(db.rs.getString("values"));
                    this.setTitle(db.rs.getString("values"));
                } else if (db.rs.getString("attributes").equals(GlobalVariables.COMPANY_LOCATION)) {
                    txtLocation.setText(db.rs.getString("values"));
                } else if (db.rs.getString("attributes").equals(GlobalVariables.COMPANY_PROPRIETOR_NAME)) {
                    txtProprietorName.setText(db.rs.getString("values"));
                } else if (db.rs.getString("attributes").equals(GlobalVariables.COMPANY_CONTACT_NO)) {
                    txtContactNo.setText(db.rs.getString("values"));
                } else if (db.rs.getString("attributes").equals(GlobalVariables.COMPANY_EMAIL_ADD)) {
                    txtEmailAdd.setText(db.rs.getString("values"));
                } else if (db.rs.getString("attributes").equals(GlobalVariables.COMPANY_SYSTEM_VERSION)) {
                    txtSystemVersionNo.setText(db.rs.getString("values"));
                    this.setTitle(this.getTitle()+" Ver. "+db.rs.getString("values"));
                }
            }
            txtCompanyName.setEnabled(false);
            txtLocation.setEnabled(false);
            txtProprietorName.setEnabled(false);
            txtContactNo.setEnabled(false);
            txtEmailAdd.setEnabled(false);
            txtSystemVersionNo.setEnabled(false);
            btnSave.setText("EDIT");
        } catch (SQLException e) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (db.con != null) {
                db.closeConnection();
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCompanyName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtProprietorName = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        txtEmailAdd = new javax.swing.JTextField();
        txtSystemVersionNo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CORE Diagnostic and Urgent Care Center, Inc.");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(6, 0, 0, 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Company Name:");
        jPanel3.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Location:");
        jPanel3.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Proprietor Name:");
        jPanel3.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Contact No.");
        jPanel3.add(jLabel4);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Email-Add:");
        jPanel3.add(jLabel6);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Version No.");
        jPanel3.add(jLabel5);

        jPanel4.setLayout(new java.awt.GridLayout(6, 0, 0, 3));

        txtCompanyName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtCompanyName);

        txtLocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtLocation);

        txtProprietorName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtProprietorName);

        txtContactNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtContactNo);

        txtEmailAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtEmailAdd);

        txtSystemVersionNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtSystemVersionNo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(588, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel10.setText("   System Information");
        jPanel6.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(jSeparator2, java.awt.BorderLayout.PAGE_START);

        jPanel9.setPreferredSize(new java.awt.Dimension(588, 80));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButton1.setMnemonic('C');
        jButton1.setText("CLOSE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_icon.png"))); // NOI18N
        btnSave.setMnemonic('S');
        btnSave.setText("SAVE");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (btnSave.getText().equals("EDIT")) {
            txtCompanyName.setEnabled(true);
            txtLocation.setEnabled(true);
            txtProprietorName.setEnabled(true);
            txtContactNo.setEnabled(true);
            txtEmailAdd.setEnabled(true);
            txtSystemVersionNo.setEnabled(true);
            txtCompanyName.requestFocus();
            btnSave.setText("SAVE");
        } else {
            String companyName = txtCompanyName.getText().trim();
            String location = txtLocation.getText().trim();
            String propreitor = txtProprietorName.getText().trim();
            String contactno = txtContactNo.getText().trim();
            String emailadd = txtEmailAdd.getText().trim();
            String versionno = txtSystemVersionNo.getText().trim();
            if (companyName.equals("")) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No Company name found. Please enter company name!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtCompanyName.requestFocus();
                return;
            }
            if (location.equals("")) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No Location found. Please enter Location!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtLocation.requestFocus();
                return;
            }
            if (propreitor.equals("")) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No Proprietor Name found. Please enter Proprietor Name!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtProprietorName.requestFocus();
                return;
            }
            if (contactno.equals("")) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No Contact Number found. Please enter Contact Number!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtContactNo.requestFocus();
                return;
            }
            if (emailadd.equals("")) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No Email Address found. Please enter Email Address!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtEmailAdd.requestFocus();
                return;
            }
            if (versionno.equals("")) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No System Version No. found. Please enter System Version No.!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtSystemVersionNo.requestFocus();
                return;
            }

            DBQueries db = new DBQueries();
            int task = 0;
            try {
                int CONFIRM = JOptionPane.showConfirmDialog(this, "Are all information correct?", "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (CONFIRM == JOptionPane.YES_OPTION) {
                    db.ConnectToDatabase();
                    db.con.setAutoCommit(false);
                    db.deleteSystemInfo();
                    task += db.insertSystemInformation(GlobalVariables.COMPANY_NAME, companyName);
                    task += db.insertSystemInformation(GlobalVariables.COMPANY_LOCATION, location);
                    task += db.insertSystemInformation(GlobalVariables.COMPANY_PROPRIETOR_NAME, propreitor);
                    task += db.insertSystemInformation(GlobalVariables.COMPANY_CONTACT_NO, contactno);
                    task += db.insertSystemInformation(GlobalVariables.COMPANY_EMAIL_ADD, emailadd);
                    task += db.insertSystemInformation(GlobalVariables.COMPANY_SYSTEM_VERSION, versionno);
                    if (task > 5) {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(null, "Saved Successfully!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        btnSave.setText("EDIT");
                        txtCompanyName.setEnabled(false);
                        txtLocation.setEnabled(false);
                        txtProprietorName.setEnabled(false);
                        txtContactNo.setEnabled(false);
                        txtEmailAdd.setEnabled(false);
                        txtSystemVersionNo.setEnabled(false);
                    } else {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(null, "Save Failed!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }

            } catch (HeadlessException | SQLException e) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                try {
                    if (db.con != null) {
                        db.con.rollback();
                    }
                } catch (SQLException ex) {
                }
            } finally {
                if (db.con != null) {
                    try {
                        db.con.commit();
                        db.closeConnection();
                    } catch (SQLException ex) {
                    }

                }

            }

        }


    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgSystemInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgSystemInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgSystemInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgSystemInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgSystemInformation dialog = new dlgSystemInformation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtProprietorName;
    private javax.swing.JTextField txtSystemVersionNo;
    // End of variables declaration//GEN-END:variables
}
