/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corediagnosticsystem;

import classes.CommonMethod;
import classes.DBQueries;
import classes.SwingUtils;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACC
 */
public class dlgUserAccount extends javax.swing.JDialog {

    private frmMain main;

    /**
     * Creates new form dlgUserAccount
     */
    public dlgUserAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.main = (frmMain) parent;
        CommonMethod.setDialogScreenLocation(main, this);
        showUserInfo();
    }

    public void showUserInfo() {
        DefaultTableModel model = (DefaultTableModel) tbUserAccount.getModel();
        int row = 0;
        DBQueries db = new DBQueries();
        try {
            CommonMethod.clearTable(tbUserAccount);
            db.ConnectToDatabase();
            db.queryUsersAccount();
            while (db.rs.next()) {
                model.insertRow(row++, new Object[]{row, db.rs.getString("emp_lastname") + ", " + db.rs.getString("emp_firstname") + " " + db.rs.getString("emp_extension") + " " + db.rs.getString("emp_middlename"), db.rs.getString("username"), db.rs.getString("role"), db.rs.getString("status"), db.rs.getString("date_created")});
            }
        } catch (SQLException e) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (db.con != null) {
                db.closeConnection();
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUserAccount = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        btnNewEmployee = new javax.swing.JButton();
        btnEditInfoEmployee = new javax.swing.JButton();
        btnEditInfoEmployee1 = new javax.swing.JButton();
        btnEditInfoEmployee2 = new javax.swing.JButton();
        btnGenerateEmployeeInfo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CORE Diagnostic and Urgent Care Center, Inc.");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setLayout(new java.awt.BorderLayout());

        tbUserAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "FULLNAME", "USERNAME", "SYSTEM ROLE", "STATUS", "DATE REGISTERED"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUserAccount.setRowHeight(25);
        tbUserAccount.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbUserAccount);
        if (tbUserAccount.getColumnModel().getColumnCount() > 0) {
            tbUserAccount.getColumnModel().getColumn(0).setMinWidth(40);
            tbUserAccount.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbUserAccount.getColumnModel().getColumn(0).setMaxWidth(40);
            tbUserAccount.getColumnModel().getColumn(2).setMinWidth(100);
            tbUserAccount.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbUserAccount.getColumnModel().getColumn(2).setMaxWidth(100);
            tbUserAccount.getColumnModel().getColumn(3).setMinWidth(100);
            tbUserAccount.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbUserAccount.getColumnModel().getColumn(3).setMaxWidth(100);
            tbUserAccount.getColumnModel().getColumn(4).setMinWidth(80);
            tbUserAccount.getColumnModel().getColumn(4).setPreferredWidth(80);
            tbUserAccount.getColumnModel().getColumn(4).setMaxWidth(80);
            tbUserAccount.getColumnModel().getColumn(5).setMinWidth(120);
            tbUserAccount.getColumnModel().getColumn(5).setPreferredWidth(120);
            tbUserAccount.getColumnModel().getColumn(5).setMaxWidth(120);
        }

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridLayout(5, 0, 0, 3));

        btnNewEmployee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNewEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_icon32.png"))); // NOI18N
        btnNewEmployee.setText("New Account");
        btnNewEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewEmployee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEmployeeActionPerformed(evt);
            }
        });
        jPanel13.add(btnNewEmployee);

        btnEditInfoEmployee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditInfoEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_con32.png"))); // NOI18N
        btnEditInfoEmployee.setText("Change Role");
        btnEditInfoEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditInfoEmployee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditInfoEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInfoEmployeeActionPerformed(evt);
            }
        });
        jPanel13.add(btnEditInfoEmployee);

        btnEditInfoEmployee1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditInfoEmployee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update_icon.png"))); // NOI18N
        btnEditInfoEmployee1.setText("Reset Password");
        btnEditInfoEmployee1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditInfoEmployee1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditInfoEmployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInfoEmployee1ActionPerformed(evt);
            }
        });
        jPanel13.add(btnEditInfoEmployee1);

        btnEditInfoEmployee2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditInfoEmployee2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        btnEditInfoEmployee2.setText("Account Status");
        btnEditInfoEmployee2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditInfoEmployee2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditInfoEmployee2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInfoEmployee2ActionPerformed(evt);
            }
        });
        jPanel13.add(btnEditInfoEmployee2);

        btnGenerateEmployeeInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGenerateEmployeeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf_icon2.png"))); // NOI18N
        btnGenerateEmployeeInfo.setText("Refresh");
        btnGenerateEmployeeInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerateEmployeeInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGenerateEmployeeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateEmployeeInfoActionPerformed(evt);
            }
        });
        jPanel13.add(btnGenerateEmployeeInfo);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(588, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel10.setText("   USERS ACOUNT LIST");
        jPanel6.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEmployeeActionPerformed
        dlgUserNew user = new dlgUserNew(main, this, true);
        SwingUtils.fadeIn(user);
    }//GEN-LAST:event_btnNewEmployeeActionPerformed

    private void btnGenerateEmployeeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateEmployeeInfoActionPerformed
        showUserInfo();
    }//GEN-LAST:event_btnGenerateEmployeeInfoActionPerformed

    private void btnEditInfoEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInfoEmployeeActionPerformed
        int rowSelected = tbUserAccount.getSelectedRow();
        if (rowSelected == -1) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No row selected. Please select a user from the table!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String employeeName = tbUserAccount.getValueAt(rowSelected, 1).toString();
        String username = tbUserAccount.getValueAt(rowSelected, 2).toString();
        if (!username.equals("")) {
            dlgUserUpdateRole update = new dlgUserUpdateRole(main, this, true, username,employeeName);
            SwingUtils.fadeIn(update);
        }
    }//GEN-LAST:event_btnEditInfoEmployeeActionPerformed

    private void btnEditInfoEmployee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInfoEmployee1ActionPerformed
         int rowSelected = tbUserAccount.getSelectedRow();
        if (rowSelected == -1) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "No row selected. Please select a user from the table!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String employeeName = tbUserAccount.getValueAt(rowSelected, 1).toString();
        String username = tbUserAccount.getValueAt(rowSelected, 2).toString();
        if (!username.equals("")) {
            dlgUserResetPassword update = new dlgUserResetPassword(main, this, true, username,employeeName);
            SwingUtils.fadeIn(update);
        }
    }//GEN-LAST:event_btnEditInfoEmployee1ActionPerformed

    private void btnEditInfoEmployee2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInfoEmployee2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditInfoEmployee2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgUserAccount dialog = new dlgUserAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditInfoEmployee;
    private javax.swing.JButton btnEditInfoEmployee1;
    private javax.swing.JButton btnEditInfoEmployee2;
    private javax.swing.JButton btnGenerateEmployeeInfo;
    private javax.swing.JButton btnNewEmployee;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbUserAccount;
    // End of variables declaration//GEN-END:variables
}
