/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * frmSplash.java
 *
 * Created on 12 30, 10, 3:05:00 PM
 */
package corediagnosticsystem;

import classes.CropImage;
import classes.ImagePanel;

import java.awt.*;
import java.awt.event.*;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;


/**
 *
 * @author abuyog
 */
public class frmSplash extends javax.swing.JFrame implements ActionListener {

    private Timer timer;
    frmMain main;
    int i = 0;

    /**
     * Creates new form frmSplash
     */
    public frmSplash() {
        initComponents();
        Dimension dimen = Toolkit.getDefaultToolkit().getScreenSize();
        CropImage crop = new CropImage();
        crop.start(ap.getWidth(), ap.getHeight(), "./src/images/core diagnostic splash.png", "./src/images/core diagnostic splash2.png");
        ImagePanel panels = new ImagePanel(new ImageIcon("./src/images/core diagnostic splash2.png").getImage());
        //set Image Icons
        Image icon = Toolkit.getDefaultToolkit().getImage("./src/images/core diagnostic splash2.png");
        setIconImage(icon);
        Dimension layer = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (layer.width - this.getSize().width) / 2;
        int height = (layer.height - this.getSize().height) / 2;
        setLocation(width, height);
        ap.add(panels);
        //ap.add(loading);
        //loading.setVisible(true);
        timer = new Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent o) {
                //nambahin i
                i += 11;
                if (i == 100) {
                    //loading.setText("Done Loading");
                    //loading.setVisible(true);
                }
                // System.out.println(i);
                //mengatur nilai loadingnya
                pBar.setValue(i);
                //kalo dah 100% yah selesai dah
                cek();
            }
        });

        timer.start();

    }

    public void cek() {
        //System.out.println(pBar.getPercentComplete());
        if (pBar.getPercentComplete() == 1.0) {
            timer.stop();
            main = new frmMain();
            main.setVisible(true);
            //main.showLogin();
            this.dispose();

        }

    }

    /*
    private void setBackGround(Dimension dimen){
        CropImage crop = new CropImage();
        crop.start(dimen.width, dimen.height, "./src/Images/backgroundbig.png", "./src/Images/backgroundbig1.png");
        ImagePanel splash = new ImagePanel(new ImageIcon("./src/Images/backgroundbig1.png").getImage());
        jPanel1.add(splash);
        
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBar = new javax.swing.JProgressBar();
        ap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pBar.setBackground(new java.awt.Color(204, 0, 255));
        pBar.setForeground(new java.awt.Color(0, 0, 153));
        pBar.setString("");
        pBar.setStringPainted(true);
        getContentPane().add(pBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 401, 990, -1));

        ap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/core diagnostic splash.png"))); // NOI18N
        ap.setBorder(new javax.swing.border.MatteBorder(null));
        ap.setDoubleBuffered(true);
        ap.setMaximumSize(new java.awt.Dimension(1368, 768));
        ap.setMinimumSize(new java.awt.Dimension(1368, 768));
        ap.setOpaque(true);
        ap.setPreferredSize(new java.awt.Dimension(1368, 768));
        ap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apFocusGained(evt);
            }
        });
        getContentPane().add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 1040, 429));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void apFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apFocusGained

    }//GEN-LAST:event_apFocusGained

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
       
       /* 
     try {
            
            // setTheme(String themeName, String licenseKey, String logoString)
            com.jtattoo.plaf.aluminium.AluminiumLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "Core Diagnostic");
            
            // select the Look and Feel
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            
            // start the demo application
           // new SimpleThemesDemo();
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
     */
        java.awt.EventQueue.invokeLater(new Runnable() {
            frmSplash a;

            public void run() {
                a = new frmSplash();
                a.setVisible(true);
            }
        });
    }

    public void actionPerformed(ActionEvent e) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ap;
    private javax.swing.JProgressBar pBar;
    // End of variables declaration//GEN-END:variables

}
